### ISSUE TITLE
Compatibility with Twig 3.0

### ISSUE THREAD

**Issue by BeyerJC** [bocharsky-bw/ActiveMenuItemBundle#5]
Hi there !

The BWExtension currently extends Twig_Extension which is deprecated since Twig 2.7 and was removed in Twig 3.0. Since composer.json does not require twig ^2.10  the extension breaks in newer applications.

There are two possible solutions.

1. restrict the twig version in the composer.json which is... not ideal i think
or
2. Change the extend to AbstractExtension and release the bundle in version 2.0

@bocharsky-bw  WDYT ?

**Comment by bocharsky-bw** [comment]
Woops! You're right! Actually, Twig is a required dependency of this bundle, so this should be listed in `require` section of composer.json. So, I think both your options are correct. In one PR we need to add Twig as a dependency and constraint it to version `^2.x`... this will be a patch fix. Then, we need another PR where we need to tweak Twig version to `^3.x` and extend the new extension class. Since no changes are required from devs who use this bundle - we can release a minor version for the 2nd PR, no need to bump the major version.

How does it sound to you? Btw, would you like to help with it and open PR for any changes you're interested in? Or maybe both PR?

I noticed that we also can simplify directory structure moving namespace prefix to the composer.json. I think it would be good to do too :)

P.S. Sorry for the slow response on it! And thank _you_ for opening this issue!

**Comment by BeyerJC** [comment]
Hey @bocharsky-bw ,

sounds good to me! I will do the changes and commit a PR after Holidays.

Merry Xmas to you btw :-)

**Comment by bocharsky-bw** [comment]
@WhiteRabbitDE Merry Xmas to you to! :)

Perfect, then looking forward to a PR from you, thanks a lot for helping with it!

**Comment by BeyerJC** [comment]
@bocharsky-bw  PRs are up as suggested by you.

So, nothing more to do here :-)  I will close the issue.

**Comment by bocharsky-bw** [comment]
@WhiteRabbitDE Thank you a lot for your help! Will take a look at PRs a bit later, already on my TODO list
